name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
    - uses: actions/checkout@v3
    
    - name: Stop containers
      run: docker compose -f "docker-compose.development.yml" down
      
    - name: Build and start containers
    - uses: isbang/compose-action@v1.1.0
      with:
        compose-file: "./docker-compose.development.yml"
