name: Docker Image CI

on:
  push:
    branches: ['develop']

jobs:
  SSH:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull source from repo
        uses: appleboy/ssh-action@master

        with:
          command_timeout: 30m
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd actions-runner/_work/voom/voom
            git pull origin develop

      - name: Setting env
        run: |
          pwd
          echo "DEPLOY_ENV=${{ secrets.DEV_REALTIME_DEPLOY_ENV }}" >> apps/realtime/.env.development
          echo "PORT=${{ secrets.DEV_REALTIME_PORT }}" >> apps/realtime/.env.development
          echo "NEXT_PUBLIC_API_URL=${{ secrets.DEV_WEB_NEXT_PUBLIC_API_URL }}" >> apps/voom-web/.env.development
          echo "NEXT_PUBLIC_STUN_GOOGLE_LIST=${{ secrets.DEV_WEB_NEXT_PUBLIC_STUN_GOOGLE_LIST }}" >> apps/voom-web/.env.development
          cat apps/voom-web/.env.development
