name: Docker Image CI

on:
  push:
    branches: ['develop']

jobs:
  SSH:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Pull source from repo
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 30m
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            whoami
            cd actions-runner/_work/voom/voom
            git pull origin develop
            docker-compose -f docker-compose.development.yaml up --build -d
